server:
  port: 8999

eureka:
  instance:
    hostname: localhost
   
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      
        - id: favourite_service
          uri: http://localhost:8080/
          predicates:
            - Path=/**

        - id: login_service
          uri: http://localhost:8282/
          predicates:
            - Path=/**
        

